[package]
name = "bff"
version = "0.1.0"
authors = ["widberg"]
edition = "2021"

[dependencies]
bff-derive = { path = "../bff-derive" }
bilge = { git = "https://github.com/widberg/bilge.git", features = [ "serde" ] }
binrw = "0.12.0"
derive_more = "0.99.17"
impl-trait-for-tuples = "0.2.2"
indexmap = { version = "2.0.0", features = ["serde"] }
itertools = { version = "0.11.0", features = [] }
lz4 = "1.24.0"
minilzo-rs = "0.6.0"
num-traits = "0.2.15"
once_cell = { version = "1.18.0", features = [] }
rayon = { version = "1.8.0", features = [] }
scanf = "1.2.1"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5.1"
xbadpcm = "0.1.1"
arcode = "0.2.4"

[dev-dependencies]
test-generator = "0.3.1"
